title: This is my awesome title!
author: GitHub User melindasterne
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome test githubpages tutorial site. I can edit this
  line in _config.yml. It will appear in my document head meta (for
  Google search results) and in my feed.xml site description.
  

# social links
github_username:  melindasterne

show_excerpts: true # set to false to remove excerpts on the homepage
